import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { ClerkProvider } from "@clerk/nextjs";




const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={inter.className}
          style={{
            width: "100%",
            height: "100%",
            background: "white",
          }}
        >
          <nav
            style={{
              width: "100%",
              background: "#39A7FF",
              fontSize: "20px",
              display: "flex",
              justifyContent: "center",
              color: "white",
            }}
          >
            <Link style={{ margin: "5px" }} href="./">
              home
            </Link>

            <Link style={{ margin: "5px" }} href="./about">
              about
            </Link>

            <Link style={{ margin: "5px" }} href="./contact">
              contact
            </Link>

            <Link style={{ margin: "5px" }} href="./signIn">
              signIn
            </Link>

            <Link style={{ margin: "5px" }} href="./signOut">
              signOut
            </Link>
          </nav>

          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
